services:

  postgres:
    image: postgres:17
    container_name: marketplace-ch8-postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: unless-stopped