// <auto-generated />
using System;
using Marketplace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marketplace.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20260802143413_MakeNavigationsOptional")]
    partial class MakeNavigationsOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marketplace.Domain.ClassifiedAd.ClassifiedAd", b =>
                {
                    b.Property<Guid>("ClassifiedAdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("ClassifiedAdId");

                    b.ToTable("ClassifiedAds");
                });

            modelBuilder.Entity("Marketplace.Domain.ClassifiedAd.Picture", b =>
                {
                    b.Property<Guid>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassifiedAdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("PictureId");

                    b.HasIndex("ClassifiedAdId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("Marketplace.Domain.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Marketplace.Domain.ClassifiedAd.ClassifiedAd", b =>
                {
                    b.OwnsOne("Marketplace.Domain.Shared.UserId", "ApprovedBy", b1 =>
                        {
                            b1.Property<Guid>("ClassifiedAdId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("ClassifiedAdId");

                            b1.ToTable("ClassifiedAds");

                            b1.WithOwner()
                                .HasForeignKey("ClassifiedAdId");
                        });

                    b.OwnsOne("Marketplace.Domain.ClassifiedAd.ClassifiedAdId", "Id", b1 =>
                        {
                            b1.Property<Guid>("ClassifiedAdId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("ClassifiedAdId");

                            b1.ToTable("ClassifiedAds");

                            b1.WithOwner()
                                .HasForeignKey("ClassifiedAdId");
                        });

                    b.OwnsOne("Marketplace.Domain.Shared.UserId", "OwnerId", b1 =>
                        {
                            b1.Property<Guid>("ClassifiedAdId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("ClassifiedAdId");

                            b1.ToTable("ClassifiedAds");

                            b1.WithOwner()
                                .HasForeignKey("ClassifiedAdId");
                        });

                    b.OwnsOne("Marketplace.Domain.ClassifiedAd.ClassifiedAdText", "Text", b1 =>
                        {
                            b1.Property<Guid>("ClassifiedAdId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("ClassifiedAdId");

                            b1.ToTable("ClassifiedAds");

                            b1.WithOwner()
                                .HasForeignKey("ClassifiedAdId");
                        });

                    b.OwnsOne("Marketplace.Domain.ClassifiedAd.ClassifiedAdTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("ClassifiedAdId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("ClassifiedAdId");

                            b1.ToTable("ClassifiedAds");

                            b1.WithOwner()
                                .HasForeignKey("ClassifiedAdId");
                        });

                    b.OwnsOne("Marketplace.Domain.ClassifiedAd.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ClassifiedAdId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.HasKey("ClassifiedAdId");

                            b1.ToTable("ClassifiedAds");

                            b1.WithOwner()
                                .HasForeignKey("ClassifiedAdId");

                            b1.OwnsOne("Marketplace.Domain.Shared.Currency", "Currency", b2 =>
                                {
                                    b2.Property<Guid>("PriceClassifiedAdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnType("text");

                                    b2.Property<int>("DecimalPlaces")
                                        .HasColumnType("integer");

                                    b2.Property<bool>("InUse")
                                        .HasColumnType("boolean");

                                    b2.HasKey("PriceClassifiedAdId");

                                    b2.ToTable("ClassifiedAds");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceClassifiedAdId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.Navigation("ApprovedBy")
                        .IsRequired();

                    b.Navigation("Id")
                        .IsRequired();

                    b.Navigation("OwnerId")
                        .IsRequired();

                    b.Navigation("Price");

                    b.Navigation("Text");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Marketplace.Domain.ClassifiedAd.Picture", b =>
                {
                    b.HasOne("Marketplace.Domain.ClassifiedAd.ClassifiedAd", null)
                        .WithMany("Pictures")
                        .HasForeignKey("ClassifiedAdId");

                    b.OwnsOne("Marketplace.Domain.ClassifiedAd.ClassifiedAdId", "ParentId", b1 =>
                        {
                            b1.Property<Guid>("PictureId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("PictureId");

                            b1.ToTable("Picture");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.OwnsOne("Marketplace.Domain.ClassifiedAd.PictureId", "Id", b1 =>
                        {
                            b1.Property<Guid>("PictureId")
                                .HasColumnType("uuid");

                            b1.HasKey("PictureId");

                            b1.ToTable("Picture");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.OwnsOne("Marketplace.Domain.ClassifiedAd.PictureSize", "Size", b1 =>
                        {
                            b1.Property<Guid>("PictureId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("PictureId");

                            b1.ToTable("Picture");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.Navigation("Id")
                        .IsRequired();

                    b.Navigation("ParentId")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.UserProfile.UserProfile", b =>
                {
                    b.OwnsOne("Marketplace.Domain.UserProfile.DisplayName", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("Marketplace.Domain.UserProfile.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("Marketplace.Domain.Shared.UserId", "Id", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Id")
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.ClassifiedAd.ClassifiedAd", b =>
                {
                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
